### ISSUE TITLE
Mismatch: Bibliography Style

### ISSUE THREAD

**Issue by realmartinlukas** [iswunistuttgart/isw_smb_diss#2]
Thank you very much for providing this helpful repo!

The University of Stuttgart's publishing guide (https://www.verbund.uni-stuttgart.de/maschinenbau/#id-18510c4e) links to this repository as well as to a .docx-template. 

The bibliography style for the .docx looks like this ![bib_docx](https://user-images.githubusercontent.com/80629699/154793706-dbddc502-7d6f-4bea-9074-cc687b4e7dbd.png)
my TeXworks renders the provided "bibliography.bib" for "diss_beispiel.tex" as ![bib-tex](https://user-images.githubusercontent.com/80629699/154793762-4e555cd6-97b8-47ad-8009-a8ded5ceb2e2.png)

I have some question regarding that:

1. Is this the latter output the intended result?
2 .Depending on (1), is this mismatch between styles a known and accepted feature?

**Comment by chhinze** [comment]
Hey,

I will check back next week with the authors of the Word template. This seems to be a problem on their side. Prevoiusly, a custom citaiton style was used, but for the SMB template we now decided on using an established citation style (i.e. the IEEE style) instead of a incomplete, self-defined one (wich was even bad, as it occupied the left third of the page for the citation keys and unnessecarily stretched the bibliography). The new citaiton style seems not to have found its way into the Word teplate yet. They will hopefully update it timely. 

So 1. the bibliography style is intended, it should be okay to write your thesis like this, I will follow up next week with a definitive answer after havong spoken with the Word template guys. 2. I wasn't aware of this, thanks for pointing out.

**Comment by realmartinlukas** [comment]
Thank you very much for the quick response and help!

**Comment by henry76** [comment]
@realmartinlukas: The word templates uses the citavi word plugin. In that plugin you can choose your bib-style for your word template. As chhinze wrote, the LaTeX template moved towards the IEEE style. Which style you use for your document, please consult with your supervisor. IMHO it is very important that you use the same style throughout the whole document!

Are you using the Citavi Word Plugin? Which Version of OS, Word, Citavi are you using?

**Comment by chhinze** [comment]
We now have an answer from the publisher. The citaiton style is free to choose (but obiusly has to be consistent throughout the document). Hence, with the current IEEE style your thesis will definitively get printed.

We will stick with the IEEE style in the LaTeX template for now, as it 

- is completely defined (in contrary to the previously used custom style)
- uses much less space

In future, we could make it customizable by the user.

**Comment by realmartinlukas** [comment]
> @realmartinlukas: The word templates uses the citavi word plugin. In that plugin you can choose your bib-style for your word template. As chhinze wrote, the LaTeX template moved towards the IEEE style. Which style you use for your document, please consult with your supervisor. IMHO it is very important that you use the same style throughout the whole document!
> 
> Are you using the Citavi Word Plugin? Which Version of OS, Word, Citavi are you using?

I am not using the Word Template / Citavi Plugin, but the the Latex document
